{'path': 'DB\\dby.db', 'stop': False, 'old_db': None, 'load_is_need': False, 'commend_list': {"'a'": 'a', '456': '456', 'max(5, 9)': '9', "print('hello')": 'None', "eval('1+2')": '3', 'min(7, 5)': '5', '7+5': '12'}, 'users': {}, 'errors': {'number_error': ('errors.NumberError', {'type_msg': 'NumberError', 'msg': 'The number of arguments is wrong.'}), 'not_connect': ('errors.NotConnect', {'type_msg': 'NotConnectError', 'msg': 'Your not connected.'}), 'name_exsist': ('errors.NameExsist', {'type_msg': 'NameExsistError', 'msg': 'The name is alredy exsist on the system'}), 'not_admin': ('errors.NotAdmin', {'type_msg': 'NotAdminError', 'msg': 'your not admin accses denied'}), 'act_not_exsist': ('errors.ActionNotExsist', {'type_msg': 'ActionNotExsist', 'msg': 'action not exsist error'}), 'user_not_in_group': ('errors.UserNotInGroup', {'type_msg': 'UserNotInGroup', 'msg': 'user not in group'}), 'group_not_exsist': ('errors.GroupNotExsist', {'type_msg': 'GroupNotExsist', 'msg': 'group zx72hovz2f das not exsist'}), 'user_not_exsist': ('errors.UserNotExsist', {'type_msg': 'UserNotExsist', 'msg': 'user not exsist on the system'}), 'data_error': ('errors.DataError', {'type_msg': 'DataError', 'msg': "invalide data ({'act': 'ask_bot', 'ask': 'hello', 'address': ('127.0.0.1', 8660)})"})}, 'server_list': set(), 'groups': {}, 'bots': {}, 'public_bots_data': {}, 'token': 0}